### ISSUE TITLE
Where is the UI-Bundle?

### ISSUE THREAD

**Issue by veenarm** [OpenLiberty/docs-generated#49]
I'm trying to play with Antora (we have it working with some content) but I'm trying to find your ui bundle?
seems it's not in any of the source repositories, but your antora playbook as it hard listed. Is this a separate generated file that's not open sourced?

**Comment by mbroz2** [comment]
hi @veenarm,
apologies for the delayed response, unfortunately we haven't been tracking issues in this repo because its contents is largely generated and updated through automation.
To answer your question, the [antora-ui is in the openliberty.io repo](https://github.com/OpenLiberty/openliberty.io/tree/prod/src/main/content/antora_ui), which includes our various buildscripts including the the ones that build the antora (docs) portion of the openlibert.io site.

If you have any more questions, please raise them in the `openliberty.io` repo (or the `docs` or `docs-playbook` repo)
